import type { Config } from 'tailwindcss'

export default <Config>{
  darkMode: 'class',
  content: [
    './components/**/*.{vue,js,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './app.vue',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#474747',
        'surface-tint': '#ba1a20',
        'inverse-on-surface': '#f1f1f1',
        'on-primary-fixed-variant': '#930010',
        'on-primary': '#ffffff',
        surface: '#f9f9f9',
        'surface-variant': '#e2e2e2',
        'outline-variant': '#e4beba',
        'tertiary-container': '#00799c',
        'surface-container-low': '#f3f3f3',
        'primary-container': '#d32f2f',
        'on-primary-fixed': '#410003',
        'surface-bright': '#f9f9f9',
        'inverse-primary': '#ffb3ac',
        'tertiary-fixed-dim': '#7bd1f8',
        'primary-fixed': '#ffdad6',
        'on-secondary-fixed': '#1b1c1c',
        'secondary-fixed': '#e4e2e1',
        primary: '#af101a',
        'on-surface': '#1a1c1c',
        background: '#f9f9f9',
        'primary-fixed-dim': '#ffb3ac',
        'on-tertiary-container': '#e9f7ff',
        'on-surface-variant': '#5b403d',
        error: '#ba1a1a',
        'surface-container-high': '#e8e8e8',
        'surface-container': '#eeeeee',
        outline: '#8f6f6c',
        'on-secondary-container': '#656464',
        secondary: '#5f5e5e',
        'on-tertiary-fixed': '#001f2a',
        'tertiary-fixed': '#bee9ff',
        'surface-dim': '#dadada',
        'on-error': '#ffffff',
        'on-background': '#1a1c1c',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#c8c6c6',
        'secondary-container': '#e4e2e1',
        'on-tertiary-fixed-variant': '#004d65',
        tertiary: '#005f7b',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e2e2e2',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary-container': '#fff2f0',
        'inverse-surface': '#2f3131',
        'surface-container-lowest': '#ffffff',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
